## Tensor Flow
## Silvia Ananda(2009106120)

In [1]:
import tensorflow as tf
import numpy as np

### Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=4., stddev=3., seed=1)
random_tensor.numpy()

array([[ 1.5660453,  8.453796 ,  4.195988 , -3.3281126,  4.297745 ],
       [ 5.773673 ,  5.778469 , -2.3687887,  1.8313084,  3.831189 ],
       [ 5.9306345,  3.207028 ,  9.5699   ,  5.703525 ,  2.8514924],
       [-0.4560299,  7.785313 ,  3.9240818,  3.206111 ,  8.598441 ],
       [-1.2289314,  2.6863213,  2.30197  ,  4.9620075,  7.398493 ]],
      dtype=float32)

In [3]:
list_utt = [[2,4,6,8,10],[12,14,16,18,20],[22,24,26,28,30],[32,34,36,38,40],[42,44,46,48,50]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [5]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[-1.0686427 , -0.7024789 ,  0.22244526, -0.10651765,
          0.15407072],
        [-0.916716  ,  0.5630016 ,  0.14035074,  0.38302082,
         -1.7716217 ],
        [ 1.1490461 , -0.07121783,  0.98920494, -0.3964655 ,
         -0.63896954],
        [-1.710124  , -0.1170314 ,  2.4165814 , -0.73353904,
          1.2930026 ],
        [-0.23136854, -0.26670742, -0.272915  , -0.39532927,
         -0.03937935]],

       [[-1.675915  ,  0.7988866 ,  0.49731058, -1.6074644 ,
         -1.5364864 ],
        [ 1.9905275 , -0.7666598 ,  0.83645785, -0.5812626 ,
          0.77222645],
        [ 0.4902348 , -0.9534847 ,  1.1787382 , -0.57640535,
          0.2214321 ],
        [-1.1900591 ,  2.0882902 , -0.1709692 ,  0.02725147,
         -0.39300203],
        [ 0.504534  ,  0.62085503,  1.3754343 ,  0.62582093,
         -0.5301588 ]],

       [[ 0.22968003, -0.51404256,  0.01495483,  0.06680353,
          1.3874606 ],
        [ 0.36123028, -0.6421525 , -0.42204922,  1.5790533 ,
          0

In [6]:
slicing[3,3,3]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.2651615>

In [7]:
slicing[3]

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.11069519,  1.3992213 ,  0.29103965,  0.18538146,  0.75623757],
       [-1.5446444 , -0.31550086,  1.2767034 , -2.000063  , -0.5481953 ],
       [-0.6448151 ,  0.33725026, -0.6346784 ,  0.34062475, -1.6528922 ],
       [ 1.1437366 ,  2.2227342 ,  0.20303072, -0.2651615 ,  0.9435222 ],
       [-0.05555218, -2.2226882 , -1.2234994 , -0.5574202 ,  0.8806993 ]],
      dtype=float32)>

In [8]:
tf.gather(slicing, indices=[2,3,3]).numpy()

array([[[ 0.22968003, -0.51404256,  0.01495483,  0.06680353,
          1.3874606 ],
        [ 0.36123028, -0.6421525 , -0.42204922,  1.5790533 ,
          0.10001177],
        [ 0.19219513, -0.43628618,  0.01935679,  0.10377029,
          0.24792454],
        [ 0.13060997, -2.2579787 ,  0.9431618 ,  0.09185912,
         -0.4575693 ],
        [ 0.85566854,  2.5686758 ,  1.4173961 , -1.0839888 ,
         -0.4457866 ]],

       [[-0.11069519,  1.3992213 ,  0.29103965,  0.18538146,
          0.75623757],
        [-1.5446444 , -0.31550086,  1.2767034 , -2.000063  ,
         -0.5481953 ],
        [-0.6448151 ,  0.33725026, -0.6346784 ,  0.34062475,
         -1.6528922 ],
        [ 1.1437366 ,  2.2227342 ,  0.20303072, -0.2651615 ,
          0.9435222 ],
        [-0.05555218, -2.2226882 , -1.2234994 , -0.5574202 ,
          0.8806993 ]],

       [[-0.11069519,  1.3992213 ,  0.29103965,  0.18538146,
          0.75623757],
        [-1.5446444 , -0.31550086,  1.2767034 , -2.000063  ,
         -0

In [10]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([ 0.98920494,  1.1787382 ,  0.01935679, -0.6346784 ,  0.603005  ],
      dtype=float32)

### Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [11]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

### Menampilkan dimensi dari kedua variable tersebut


In [12]:
random_tensor.shape

TensorShape([5, 5])

In [13]:
prime_tensor.shape

TensorShape([5, 5])

### Menampilkan hasil dari perhitungan aritmatika 2 variable tersebut (Gunakan minimal 5 operator)

In [15]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n9. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n10. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n14. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n15. Minimum :",tf.math.minimum(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[  3.5660453  11.453796    9.195988    3.6718874  15.297745 ]
 [ 18.773674   22.77847    16.63121    24.831308   32.83119  ]
 [ 36.930634   40.207027   50.5699     48.703526   49.851494 ]
 [ 52.54397    66.78532    64.92408    74.20611    81.59844  ]
 [ 77.77107    85.686325   91.30197   101.962006    8.398493 ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[ 0.43395472 -5.4537964   0.8040118  10.328113    6.702255  ]
 [ 7.226327   11.221531   21.36879    21.168692   25.168812  ]
 [25.069366   33.792973   31.4301     37.296474   44.148506  ]
 [53.45603    51.214687   57.07592    67.79389    64.40156   ]
 [80.22893    80.313675   86.69803    92.037994   -6.398493  ]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[  3.1320906  25.36139    20.97994   -23.296787   47.275196 ]
 [ 75.05775    98.23398   -45.006985   42.120094  111.10448  ]
 [183.84967   118.660034  392.36588   245.25157   134.02014  ]
 [-24.169584  459.33347   239.36899

In [16]:
tf.argmax(random_tensor, axis=0).numpy()#max baris random_tensor

array([2, 0, 2, 2, 3], dtype=int64)

In [17]:
tf.argmax(random_tensor, axis=1).numpy()#max kolom random_tensor

array([1, 1, 2, 4, 4], dtype=int64)

In [18]:
tf.argmin(random_tensor, axis=0).numpy()#min baris random_tensor

array([4, 4, 1, 0, 2], dtype=int64)

In [19]:
tf.argmin(random_tensor, axis=1).numpy()#min kolom random_tensor

array([3, 2, 4, 0, 0], dtype=int64)

### Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [20]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#penggabungan baris

array([[ 1.5660453,  8.453796 ,  4.195988 , -3.3281126,  4.297745 ],
       [ 5.773673 ,  5.778469 , -2.3687887,  1.8313084,  3.831189 ],
       [ 5.9306345,  3.207028 ,  9.5699   ,  5.703525 ,  2.8514924],
       [-0.4560299,  7.785313 ,  3.9240818,  3.206111 ,  8.598441 ],
       [-1.2289314,  2.6863213,  2.30197  ,  4.9620075,  7.398493 ],
       [ 2.       ,  3.       ,  5.       ,  7.       , 11.       ],
       [13.       , 17.       , 19.       , 23.       , 29.       ],
       [31.       , 37.       , 41.       , 43.       , 47.       ],
       [53.       , 59.       , 61.       , 71.       , 73.       ],
       [79.       , 83.       , 89.       , 97.       ,  1.       ]],
      dtype=float32)

In [21]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()#penggabungan kolom

array([[ 1.5660453,  8.453796 ,  4.195988 , -3.3281126,  4.297745 ,
         2.       ,  3.       ,  5.       ,  7.       , 11.       ],
       [ 5.773673 ,  5.778469 , -2.3687887,  1.8313084,  3.831189 ,
        13.       , 17.       , 19.       , 23.       , 29.       ],
       [ 5.9306345,  3.207028 ,  9.5699   ,  5.703525 ,  2.8514924,
        31.       , 37.       , 41.       , 43.       , 47.       ],
       [-0.4560299,  7.785313 ,  3.9240818,  3.206111 ,  8.598441 ,
        53.       , 59.       , 61.       , 71.       , 73.       ],
       [-1.2289314,  2.6863213,  2.30197  ,  4.9620075,  7.398493 ,
        79.       , 83.       , 89.       , 97.       ,  1.       ]],
      dtype=float32)

### Menampilkan hasil sorting dari kedua variable di atas. (descending)

In [22]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 8.453796 ,  4.297745 ,  4.195988 ,  1.5660453, -3.3281126],
       [ 5.778469 ,  5.773673 ,  3.831189 ,  1.8313084, -2.3687887],
       [ 9.5699   ,  5.9306345,  5.703525 ,  3.207028 ,  2.8514924],
       [ 8.598441 ,  7.785313 ,  3.9240818,  3.206111 , -0.4560299],
       [ 7.398493 ,  4.9620075,  2.6863213,  2.30197  , -1.2289314]],
      dtype=float32)

In [23]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [24]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [25]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])